name: GitHub Contribution Booster

on:
  schedule:
    - cron: "35 22 * * *" #Runs every day at 22:35 UTC
  push:
    branches:
      - main

jobs:
  contribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any other dependencies if needed

      - name: Read and update commit count
        run: |
          if [ ! -f count.txt ]; then echo "0" > count.txt; fi
          COUNT=$(cat count.txt)
          COUNT=$((COUNT + 1))
          echo "$COUNT" > count.txt

      - name: Run Python script
        run: python date.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add count.txt
          git commit -m "Automated commit #$COUNT" || echo "No changes to commit"
          git push
